---
- name: Install CMD release package
  apt: 
    deb: "{{ release_url }}"
  when: release_url is defined

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: latest

- name: Add APT key of UMD repository
  apt_key:
    url: "http://repository.egi.eu/sw/production/umd/UMD-DEB-PGP-KEY"
    state: present
  when: verification_repofile is defined or cmd_enable_candidate_repo

- name: Enable candidate repository
  lineinfile:
    dest: /etc/apt/sources.list
    line: 'deb http://repository.egi.eu/sw/production/cmd-os/candidate/1/ubuntu/ xenial-updates main'
  when: cmd_enable_candidate_repo

- name: Remove i386 architecture
  shell: "dpkg --remove-architecture i386"
  when: cmd_enable_candidate_repo

- name: Update cache
  shell: "apt-get update"
  #apt:
  #  update_cache: yes
  #  cache_valid_time: 10

- name: Install OpenStack cloud-archive ppa
  command: "add-apt-repository -y cloud-archive:{{ cmd_openstack_release }}"
