---
- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: latest

- name: Add APT key of UMD repository
  apt_key:
    url: "http://repository.egi.eu/sw/production/umd/UMD-DEB-PGP-KEY"
    state: present
  when: verification_repofile is defined or enable_candidate_repo is defined

- name: Enable candidate repository
  lineinfile:
    dest: /etc/apt/sources.list
    line: 'deb http://repository.egi.eu/sw/production/cmd-os/candidate/1/ubuntu/ xenial-updates main'

- name: Update cache
  apt:
    update_cache: yes

- name: Install OpenStack cloud-archive ppa
  command: "add-apt-repository -y cloud-archive:mitaka"
