---
- name: OS specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: Check valid CMD version
  debug: msg:"CMD version {{ release }} not known!"
  when: (release is not defined) or (release > 1)

- name: Install CMD release package
  package: {{ release_url }}
  when: release_url is defined

- name: Deploy Debian-specific
  include: debian.yml
  when: (ansible_distribution == "Debian") or (ansible_distribution == "Ubuntu")

- name: Deploy RedHat-specific
  include: redhat.yml
  when: (ansible_distribution == "RedHat") or (ansible_distribution == "CentOS")

- name: Download verification repository files
  get_url: url={{ item }} dest={{ sources_dir }}
  with_items: 
    - "{{ verification_repofile|default([]) }}"
  when: verification_repofile is defined

- name: Update APT cache
  apt:
    update_cache: yes
  when: (ansible_distribution == "Debian") and (release == 1)
