---
- name: OS specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: Check valid CMD version
  debug: msg:"CMD version {{ release }} not known!"
  when: (release is not defined) or (release > 1)

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: latest
  when: (ansible_distribution == "Debian")

- name: Install OpenStack cloud-archive ppa
  command: "add-apt-repository -y cloud-archive:mitaka"
  when: (ansible_distribution == "Debian") and (release == 1)

- name: Install OpenStack RDO
  package: name=centos-release-openstack-mitaka
  when: (ansible_distribution == "CentOS") and (release == 1)

- name: Download verification repository files
  get_url: url={{ item }} dest={{ sources_dir }}
  with_items: 
    - "{{ verification_repofile }}"
  when: verification_repofile is defined 
