---
# tasks file for ansible-role-cmd
- name: Read OS specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: Check valid CMD version
  debug: msg="CMD version {{ cmd_release }} not known!"
  when: (cmd_release is not defined) or (cmd_release > 1)

- name: Deploy Debian-specific
  include: debian.yml
  when: ((ansible_os_family | lower) == "debian")

- name: Deploy RedHat-specific
  include: redhat.yml
  when: ((ansible_os_family | lower) == "redhat")

- name: Download verification repository files
  get_url: url={{ item }} dest={{ sources_dir }}
  with_items: 
    - "{{ verification_repofile|default([]) }}"
  when: verification_repofile is defined

- name: Update APT cache
  apt:
    update_cache: yes
  when: ((ansible_os_family | lower) == "debian") and (cmd_release == 1)
