---
# tasks file for ansible-role-cmd

- name: Add CMD-OS repository
  block:
  - yum_repository:
      name: cmd-os
      description: CMD-OS 1
      baseurl: http://repository.egi.eu/sw/production/cmd-os/1/centos7/$basearch/base
      gpgkey: http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY
  - yum_repository:
      name: cmd-os-updates
      description: CMD-OS 1-updates
      baseurl: http://repository.egi.eu/sw/production/cmd-os/1/centos7/$basearch/updates
      gpgkey: http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY

- name: Add CAs repository
  yum_repository:
    name: EGI-trustanchors
    description: EGI trustanchors
    baseurl: http://repository.egi.eu/sw/production/cas/1/current/
    gpgkey: http://repository.egi.eu/sw/production/cas/1/GPG-KEY-EUGridPMA-RPM-3

- name: Install OS repository for {{ cmd_os_release }}
  package:
    name: "centos-release-openstack-{{ cmd_os_release }}"
    state: present
  when: cmd_os_enable_rdo

- name: OS specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: Check valid CMD version
  debug: msg:"CMD version {{ release }} not known!"
  when: (release is not defined) or (release > 1)

- name: Deploy Debian-specific
  include: debian.yml
  when: (ansible_os_family | lower) == "debian")

- name: Deploy RedHat-specific
  include: redhat.yml
  when: (ansible_os_family | lower) == "redhat")

- name: Download verification repository files
  get_url: url={{ item }} dest={{ sources_dir }}
  with_items: 
    - "{{ verification_repofile|default([]) }}"
  when: verification_repofile is defined

- name: Update APT cache
  apt:
    update_cache: yes
  when: (ansible_distribution == "Debian") and (release == 1)
