---
- name: Install CMD release package
  yum: 
    name: "{{ release_url[cmd_distribution] }}"
  when: release_url is defined

- name: Enable CMD-OS candidate repository - base
  yum_repository:
    name: CMD-OS-1-candidate-base
    description: CMD-OS 1 candidate base (CentOS 7)
    file: CMD-OS-1-candidate
    baseurl: http://repository.egi.eu/sw/production/cmd-os/candidate/1/centos7/$basearch/base
    enabled: yes
    gpgcheck: yes
    protect: yes
    priority: 1
    gpgkey: http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY
  when: cmd_enable_candidate_repo and cmd_distribution == "cmd-os"

- name: Enable CMD-OS candidate repository - updates
  yum_repository:
    name: CMD-OS-1-candidate-updates
    description: CMD-OS 1 candidate updates (CentOS 7)
    file: CMD-OS-1-candidate
    baseurl: http://repository.egi.eu/sw/production/cmd-os/candidate/1/centos7/$basearch/updates
    enabled: yes
    gpgcheck: yes
    protect: yes
    priority: 1
    gpgkey: http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY
  when: cmd_enable_candidate_repo and cmd_distribution == "cmd-os"

- name: Enable CMD-ONE candidate repository - base
  yum_repository:
    name: CMD-ONE-1-candidate-base
    description: CMD-ONE 1 candidate base (CentOS 7)
    file: CMD-ONE-1-candidate
    baseurl: http://repository.egi.eu/sw/production/cmd-one/candidate/1/centos7/$basearch/base
    enabled: yes
    gpgcheck: yes
    protect: yes
    priority: 1
    gpgkey: http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY
  when: cmd_enable_candidate_repo and cmd_distribution == "cmd-one"

- name: Install OpenStack RDO
  package: name=centos-release-openstack-{{ cmd_openstack_release }}
  when: (ansible_distribution == "CentOS") and (cmd_release == 1) and (cmd_distribution == "cmd-os") and (cmd_openstack_release != "mitaka")

- name: Install OpenStack RDO (workaround for mitaka)
  yum:
    name: "http://linuxsoft.cern.ch/cern/centos/7/cern/x86_64/Packages/centos-release-openstack-mitaka-1-2.el7.cern.noarch.rpm" 
  when: (ansible_distribution == "CentOS") and (cmd_release == 1) and (cmd_distribution == "cmd-os") and (cmd_openstack_release == "mitaka")
